apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
  - name: test
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: first-volume
  volumes:
  - name: first-volume
    hostPath:
      path: /mydata
      type: Directory
